x-proxy-service-conf: &proxy-service-conf
  image: chocolatefrappe/ssh-proxy-client:local
  environment:
    - REMOTE_USER=${REMOTE_USER:?please set REMOTE_USER variable}
    - REMOTE_HOST=${REMOTE_HOST:?please set REMOTE_HOST variable}
    - REMOTE_PORT
  secrets:
    - source: private_key
      target: /keys.d/private_key
      mode: 0600
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 64M
    restart_policy:
      delay: 15s
      window: 120s
secrets:
  private_key:
    file: key

services:
  example:
    <<: *proxy-service-conf
    command: -R 0.0.0.0:8081:192.168.131.254:8081
